name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        # Install 'bats' for testing framework. 'shellcheck' and 'make' are pre-installed on ubuntu-latest.
        run: sudo apt-get update && sudo apt-get install -y bats shellcheck coreutils libdigest-sha-perl

      - name: Run Shellcheck linter
        # Execute lint target defined in Makefile
        run: make lint

      - name: Run native and perl tests
        # Execute all standard test suites
        run: make test-all

      - name: Build and test standalone binary
        # Execute build and verify distributable binary
        run: make test-dist
