#!/usr/bin/env bats
#
# tests/integration/02_check_mode.bats
# Integration Test: Check Mode (-c)
#
# Responsibility: Validate the 'check' mode functionality using real files
# generated by system tools, ensuring correct status reporting and exit codes.

load '../test_helper'

setup() {
  # 1. Load Constants
  load_lib "constants.sh"

  # 2. Create a secure temporary directory sandbox
  TEST_DIR="$(mktemp -d "${BATS_TMPDIR}/checkit_check_mode_XXXXXX")"

  # 3. Create a real data file inside the sandbox
  DATA_FILE="${TEST_DIR}/data_critical.txt"
  echo "System critical content for verification" >"$DATA_FILE"

  # 4. Generate REAL checksum files using system tools
  # We use absolute paths to avoid 'cd' issues during test execution
  SUM_SHA256="${TEST_DIR}/checksums.sha256"

  if command -v sha256sum >/dev/null; then
    sha256sum "$DATA_FILE" >"$SUM_SHA256"
  fi

  SUM_MD5="${TEST_DIR}/checksums.md5"
  if command -v md5sum >/dev/null; then
    md5sum "$DATA_FILE" >"$SUM_MD5"
  fi
}

teardown() {
  # Clean up the entire sandbox directory
  rm -rf "$TEST_DIR"
}

@test "Integration: checkit -c verifies SHA-256 sumfile and outputs per-file status" {
  if [ ! -f "$SUM_SHA256" ]; then skip "sha256sum tool missing"; fi

  run "$CHECKIT_EXEC" -c "$SUM_SHA256"

  assert_success
  # Expect status OK and the filename
  assert_output --partial "[OK]"
  assert_output --partial "data_critical.txt"
}

@test "Integration: checkit -c verifies MD5 sumfile and outputs per-file status" {
  if [ ! -f "$SUM_MD5" ]; then skip "md5sum tool missing"; fi

  run "$CHECKIT_EXEC" -c "$SUM_MD5"

  assert_success
  assert_output --partial "[OK]"
  assert_output --partial "data_critical.txt"
}

@test "Integration: checkit -c fails cleanly on checksum mismatch" {
  # Create a corrupted sum file inside the sandbox
  local bad_sum="${TEST_DIR}/bad.sha256"

  # Generate a dummy hash (64 chars) that won't match the file content
  local fake_hash
  fake_hash=$(printf '0%.0s' {1..64})

  # Important: Checkit expects "HASH  FILENAME"
  echo "${fake_hash}  ${DATA_FILE}" >"$bad_sum"

  run "$CHECKIT_EXEC" -c "$bad_sum"

  # Should fail with integrity error
  assert_failure "$EX_INTEGRITY_FAIL"

  # Ensure NO success message is printed for the failed file
  refute_output --partial "[OK]"
  assert_output --partial "FAILED"
}

@test "Integration: checkit -c fails if sumfile does not exist" {
  run "$CHECKIT_EXEC" -c "${TEST_DIR}/ghost_file.txt"

  # Should fail in identifying the file
  assert_failure "$EX_OPERATIONAL_ERROR"
}

@test "Integration: checkit -c skips files missing from disk (default behavior)" {
  # Create a sumfile referencing a non-existent file
  local missing_sum="${TEST_DIR}/missing.sha256"
  local valid_hash
  valid_hash=$(printf 'a%.0s' {1..64})

  echo "${valid_hash}  ${TEST_DIR}/does_not_exist.txt" >"$missing_sum"

  run "$CHECKIT_EXEC" -c "$missing_sum"

  # By default, missing files trigger an integrity failure (unless ignored)
  assert_failure "$EX_INTEGRITY_FAIL"
  assert_output --partial "MISSING"
}
